name: Build Vaultwarden for Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Build with SQLite support
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev pkg-config
        cargo build --release --features sqlite

    - name: Upload vaultwarden binary
      uses: actions/upload-artifact@v3
      with:
        name: vaultwarden-x86_64
        path: target/release/vaultwarden
