name: Build Vaultwarden for Linux

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install SQLite dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libsqlite3-dev pkg-config

    - name: Build Vaultwarden with SQLite
      run: cargo build --release --features sqlite

    - name: Upload vaultwarden binary
      uses: actions/upload-artifact@v4
      with:
        name: vaultwarden-x86_64
        path: target/release/vaultwarden
